### ISSUE TITLE
prepNTFS 

### ISSUE THREAD

**Issue by TetzkatLipHoka** [aldostools/webMAN-MOD#5]
Since about v1.34.06 i've a problem when detecting Games in ISO-format from NTFS-Drive, about half of the Games is found and listed corretly in Webman, everything after that is another link to "last" found game which is "Star Wars - Force Unleashed 2".
XMB shows them correctly also mM and irisMAN do.
Just retried again with 1.40.02 and newest prepNTFS, still the same problem.

**Comment by aldostools** [comment]
Please try increasing the plugin memory to MAX.

If that doesn't work, please send to my email aldo@aldostools.org a
list of all the files in your ntfs:/PS3ISO and in /dev_hdd0/tmp/wmtmp

So I can analyze what is the issue.

On 1/6/15, TetzkatLipHoka <notifications@github.com> wrote:
> Since about v1.34.06 i've a problem when detecting Games in ISO-format from
> NTFS-Drive, about half of the Games is found and listed corretly in Webman,
> everything after that is another link to "last" found game which is "Star
> Wars - Force Unleashed 2".
> XMB shows them correctly also mM and irisMAN do.
> Just retried again with 1.40.02 and newest prepNTFS, still the same
> problem.
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/aldostools/webMAN-MOD/issues/5


-- 
Aldo Vargas
http://www.aldostools.org

**Comment by TetzkatLipHoka** [comment]
Mail send yesterday, if you need anything else let me know.

**Comment by aldostools** [comment]
Thanks for the files. The issue should be solved in 1.41.04.

**Comment by TetzkatLipHoka** [comment]
Im sorry i've to say but that actualy didnt even improve.

Updated webMAN to .04 and refreshed via prepNTFS:
First attemp the multiple Versions of Force Unleashed disappeared but the not shown games didnt show up (Just 2 Monkey Island 5 Parts did show on Bottom/Left of Page overlapping each other.

After clearing wmtmp and history and rescanning with prepNTFS iam back to old behaviour: lots of Star Wars - Force Unleashed 2 entrys followed by 2 overlapping Monkey Island 5 icons.

Tried with Min and Max Plugin-Size, same behaviour.


Just tried renaming the Force Unleashed ISO
Renamed it to ISO_ and rescanned:
Same behaviour BUT the always repeated game is now SingStar Rocks! (Germany)
Bottom/Left is still one Monkey Island Logo overlapped by Last Of Us


Using webMANs RefreshXML/HTML Buttons isnt changeing anything either.
  ----- Original Message -----

**Comment by aldostools** [comment]
The issue was originally fixed for the games listing. After your 2nd message, I noticed that the issues was still in the file listing. It was caused by a very long name in one of the entries of Monkey Island.

The issue in the file listing should be fixed in the commit "6223623" of 1.41.05 (Jan 05, 2015):
- Reverted file listing buffer to 512 bytes (to support longer file names)

**Comment by TetzkatLipHoka** [comment]
Hi again.

There are good and bad news:
Good: I can confirm that the problem is about the Monkey Island 5-ISO's
Bad: Tried webMAN v1.40.06 with prepNTFS v1.07 and the problem is still present/reproducable.
Moved the MI5 ISOs to a subfolder, rescanned and list showed up properly
  ----- Original Message -----

**Comment by aldostools** [comment]
As I mentioned earlier, the issue is due the name of your "Monkey Island" game is too long.
If you make it shorter the issue should solved.

Anyway I added additional checks scanning content in HTML for games with file names too long, so: 
the issue should be completely solved in the commit "aaedbdf":

- Skip entry if path is too long in scanning content in html.
(Try truncating display name up to 32 bytes before skip entry)

**Comment by TetzkatLipHoka** [comment]
Ahhhh i see.
Just tried the .07 which works like a charm.
MI 1 & 4 are ignored (as expected) but everything else shows just fine, thanks :)
  ----- Original Message -----
