### ISSUE TITLE
PrepISO 1.29 Game Name XMB

### ISSUE THREAD

**Issue by ozapft** [aldostools/webMAN-MOD#626]
Hello Aldo,

I've found the following problem with the new PrepISO 1.29 

Version webMAN_MOD_1.47.37

The PS3 ISOs are stored on an external NTFS Drive.
The name for an ISO is for example ac1_bd.iso

With Prepiso 1.29 the game is listed in XMB with exactly this file name. 
With Prepiso 1.28 the game is listed with the Name Assassin's Creed in XMB

The game ID BLES00158 is not listed with 1.29 but listed with 1.28 when activated in settings of webman_mod. (path+ID)

-> 1.29 uses the File Name for XMB
1.28 uses the Name of the Game extracted from the ISO.
The old behaviour was much better in my opinion.

Thank you for your work.

**Comment by aldostools** [comment]
webMAN MOD has a PARAM.SFO option in /setup.ps3 to list the name of the games on XMB:
- Checked = The name obtained from PARAM.SFO 
- Unchecked = The file name of the ISO is used

Verify if your settings have the option PARAM.SFO unchecked.

prepISO basically generates a cache file *.ntfs[PS3ISO] in /dev_hdd0/tmp/wmtmp and extracts the ICON0 and PARAM.SFO

If the PARAM.SFO is not found or has a different name, that could be the reason why you're getting a different behavior.

Please verify the option in /setup and check if the PARAM.SFO and .ntfs[PS3ISO] have the same file name is /dev_hdd0/tmp/wmtmp. Provide a picture of the folder if you find it necessary.

**Comment by ozapft** [comment]
With Prepiso 1.29 the file in wmtmp ist named ac1_bd.iso.SFO
With Prepiso 1.28 ac1_bd.SFO

Same with the .NTFS[PS3ISO] File.
1.29 ac1_bd.iso.ntfs[PS3ISO]
1.28 ac1_bd.ntfs[PS3ISO]

The ISO File on NTFS Drive is ac1_bd.iso

In WebmanMod the Option Param.sfo is checked.

**Comment by aldostools** [comment]
From what you describe, the file should be listed as "Assassin's Creed" due the SFO and the .ntfs[PS3ISO] have the same name in /dev_hdd0/tmp/wmtmp

Any I will try to reproduce your issue. Hopefully I can find why you get the wrong name.

**Comment by aldostools** [comment]
I think I found the causes of the issue. Indeed they were 2 causes:
1- webMAN MOD was searching for .SFO in tmp/wmtmp without the file extension.
2- The other problem was when /dev_ntfs was checked. It was generating the cached file without extension.

I updated the installers in github/brewology and the online update server. So  you can download and install the new installer to test if the new version fixes your issue.

**Comment by ozapft** [comment]
Today I´ve tested the new version of webMan-MOD with PrepISO 1.29

It now works with PrepISO 1.29.  The file is listed as "Assassin's Creed" 
Thank you!

INFO:

However, the naming of the files in tmp/wmtmp is still a little bit inconsistent between internal and external version of prepISO. 

With PrepISO 1.28, an ac1_bd.iso file was treated as follows: 
ac1_bd.SFO
ac1_bd.PNG
ac1_bd.ntfs[PS3ISO] 

now with PrepISO 1.29 the suffix .iso is included in the file name. 
ac1_bd.iso.SFO 
ac1_bd.iso.PNG 
ac1_bd.iso.ntfs[PS3ISO]. 

However, the internal webMAN MOD version of PrepISO does not do so. 
The .iso suffix is not included. (/dev_ntfs  checked)

Here a file ac1_bd.ntfs[PS3ISO] is generated. 

In addition, no .SFO file and no .PNG file is generated. 

(Aditional information: PSX .bin Files are not found with internal version.)

**Comment by aldostools** [comment]
Thank you for your feedback. I'll check it later. 
Right now I am not in mood due a sibling died today 😢 

> In addition, no .SFO file and no .PNG file is generated.

That is normal, due .SFO and .PNG extraction require extra processing or mounting each ISO during the scanning.

They are extracted when the game is mounted. prepISO does it during the scanning due it doesn't have the memory limitations existing in the sprx plugin.

> (Aditional information: PSX .bin Files are not found with internal version.)

There is an issue with libntfs_prx.a that stops scanning if a second scanning is performed.
This is fixed if the system is restarted. I still have to investigate why it is happening.

**Comment by ozapft** [comment]
My sincere condolences Aldo.

**Comment by ozapft** [comment]
I've tested the internal prepntfs again after your commit. It's still not working.

**Comment by aldostools** [comment]
> I've tested the internal prepntfs again after your commit. It's still not working.

Please verify that you installed the latest build. Re-download again the pkg in case the problem persists.

I tested it last night and the internal prepNTFS was using the same file names as prepISO 1.29

Note: If the SFO exists with the old name, it will use that file name to take advange of the existing file.

**Comment by ozapft** [comment]
I´ve checked it again.
First i´ve deleted again all files in tmp/wmtmp

An ac1_bd.iso.ntfs[PS3ISO] is generated. 
After launching the game the generated SFO and PNG files are without the suffix .iso.
ac1_bd.SFO
ac1_bd.PNG
It should be ac1_bd.iso.SFO and ac1_bd.iso.PNG.

**Comment by aldostools** [comment]
Ah I think that issue is in the mount module... I will check that and let you know when I get it fixed.

**Comment by ozapft** [comment]
I've tested it again.
The generated SFO and PNG files are still without the suffix .iso.

**Comment by aldostools** [comment]
It's weird... I tested it again and it was generating the .SFO and .PNG with the file extension + .SFO or .PNG

I will continue checking in the weekend. Thanks for your feedback.

**Comment by aldostools** [comment]
I tested the latest commit one more time and it seems it's working fine.

Before mount, I have ab.iso.ntfs[PS3ISO] without SFO and PNG:
![image](https://user-images.githubusercontent.com/974897/157911976-5bf1e07d-0db9-4538-afe4-8bda37434b03.png)

After mount ab.iso.PNG and ab.iso.SFO were created:
![image](https://user-images.githubusercontent.com/974897/157912081-3940a93c-9acb-4e1b-a153-71e9c25f225d.png)

If you still get the file without the extension, please provide me a step-by-step procedure to reproduce the bug.


EDIT:
In the commit below I fixed a condition that I was not testing: when the SFO and PNG exists extracted in exFAT/NTFS.

**Comment by ozapft** [comment]
I will test it on Sunday.

**Comment by ozapft** [comment]
Is working fine now. All files have now the suffix .iso.

Thank you!!

A small info for prepISO 1.29. The german translation in param.sfo file is wrong.
Halten X bestehende zu halten Cache-Dateien  ->  X halten um vorhandene Cache-Dateien zu behalten

**Comment by aldostools** [comment]
Danke für dein Feedback mein lieber Freund!
