### ISSUE TITLE
[Bug] System crash with the version switch combo

### ISSUE THREAD

**Issue by PS3-Pro** [aldostools/webMAN-MOD#672]
A friend of mine made a new video about webMAN and noticed that sytem crashes after using L1+R1+△ to switch the webman version as you can see here: https://youtu.be/rdK74qf5qiw?t=679

I just don't know if this only happens when the FPS counter is activated or not, as I couldn't test it because I'm far from my console now.

**Comment by aldostools** [comment]
Try updating webMAN MOD again. Yesterday i fixed a bug that caused loading vsh modules multiple times.  This bug affected the new combo  L1+R1+△

**Comment by LouisGarry** [comment]
Aldo, is the latest wMM after unloading the FPS Counter can't be loaded again?  have to reboot PS3.

I'm use HEN 3.0.3

Thanks.

**Comment by aldostools** [comment]
Try updating to the latest version using the online updater? Reboot after update.

Please report back if the issue is still present after update. Thanks.

This commit should include the fix 2814ac178ae1f0c1acaaa312c28d91a663e7b22c

**Comment by LouisGarry** [comment]
Thank you for the feedback.
Just updated, the issue is still present.

**Comment by aldostools** [comment]
Ok, thank you for your feedback. I will check it later today after work.

It is weird because I was working and testing that feature yesterday.

**Comment by aldostools** [comment]
I did a quick test before a meeting, and the FPS worked fine after between Full / Lite editions.

IMPORTANT: It doesn't allow L3+R3 to load FPS while the XML is being scanned or when a game is being mounted.

Make sure that refresh XML is not being performed while you press L3+R3.

**Comment by aldostools** [comment]
@LouisGarry if you disabled CFW syscalls the FPS plugin cannot be loaded.

I added 3 beeps in the latest build to provide feedback that the combo was recognized but the action is not allowed.

**Comment by RandQalan** [comment]
I have same problem on cfw 4.88 and 4.84 on system  CECH lo1
Can not switch between light and full version lock everytime.

**Comment by aldostools** [comment]
> I have same problem on cfw 4.88 and 4.84 on system CECH lo1 Can not switch between light and full version lock everytime.

Update NOW using webMAN Games > webMAN Setup > Update webMAN MOD > Install. Reboot and test again.

The plugin is working fine on my slim CECH 2000... I don't think the feature has different behavior on different models.

**Comment by LouisGarry** [comment]
> @LouisGarry if you disabled CFW syscalls the FPS plugin cannot be loaded.
> 
> I added 3 beeps in the latest build to provide feedback that the combo was recognized but the action is not allowed.

The latest update is working fine, thanks Aldo.

**Comment by RandQalan** [comment]
Same here now thanks.
